/* Action types */

// Survey values
export const UPDATE_QUESTION_TYPE = "UPDATE_QUESTION_TYPE";
export const UPDATE_QUESTION_TEXT = "UPDATE_QUESTION_TEXT";
export const UPDATE_QUESTION_CHOICES = "UPDATE_QUESTION_CHOICES";
export const UPDATE_QUESTION_ANSWER = "UPDATE_QUESTION_ANSWER";
export const ADD_QUESTION = "ADD_QUESTION";
export const LOAD_QUESTION = "LOAD_QUESTION";